[package]
name = "zrpc-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.3.12"
config = "0.13.3"
log = "0.4.19"
serde = "1.0.177"
serde_json = "1.0.104"
tonic = "0.9"
